/**
 * @file mls_types.h
 * @brief Describes LIN data types
 * @internal
 *
 * @copyright (C) 2016-2018 Melexis N.V.
 * git flash edb9c687
 *
 * Melexis N.V. is supplying this code for use with Melexis N.V. processor based microcontrollers only.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY,
 * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.  MELEXIS N.V. SHALL NOT IN ANY CIRCUMSTANCES,
 * BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @endinternal
 *
 * @ingroup mlx_lin_slave_api
 *
 * @details Melexis LIN Slave data types
 */

#ifdef UNITTEST
#include "mls_api.h"
#endif

#ifndef MLS_API_H_
#error "The file can't be included directly but via mls_api.h"
#endif /* MLS_API_H_ */

#ifndef MLS_TYPES_H_
#define MLS_TYPES_H_

#include <stdint.h>
#include <stdbool.h>

#include "mls_consts.h"     /* LIN Module constants */


/*-----------------------------------------------------------------------------
 * Constants and macros                 (scope: module-local)
 */

#ifndef PACKED
#define PACKED __attribute__((packed))
#endif


/*-----------------------------------------------------------------------------
 * Typedefs					            (scope: global)
 */

/* ml_Bool_t */
typedef enum {
    ML_TRUE = 1u,
    ML_FALSE = 0u
} ml_Bool_t;

/* ml_StateChangeEvent_t */
typedef enum {
    ML_ENABLED = ML_TRUE,
    ML_DISABLED = ML_FALSE
} ml_StateChangeEvent_t;

/* ml_SleepMode_t */
typedef enum {
    ML_LIGHTSLEEP = ML_FALSE,
    ML_DEEPSLEEP = ML_TRUE
} ml_SleepMode_t;

/* ml_LinVersion_t */
typedef enum {
    ML_VER_DEFAULT = 0,
    ML_VER_1_3 = 8,
    ML_VER_2_X = 9
} ml_LinVersion_t;

/* ml_DataTransmittedEvent_t */
typedef enum {
    ML_END_OF_TX_ENABLED = ML_TRUE,
    ML_END_OF_TX_DISABLED = ML_FALSE
} ml_DataTransmittedEvent_t;

/* ml_Status_t */
typedef enum {
    ML_SUCCESS = 0u,
    ML_FAILURE = 1u,
    ML_TIMEOUT = 2u
} ml_Status_t;

/*
 * STOP bit transmission error (erStopBitTX) is generated by LIN ISR (mlx16)
 * based on erTXCOL LIN Module error and mostly required for SAE J2602.
 * Range of error codes reported by LIN Module is 0x00-0x0F
 */
#define mlx16_erStopBitTX     0x10    /* Error during STOP bit transmission */

/* ml_LinError_t */
typedef enum {
    ml_erShortDone       = erSHORTDONE,
    ml_erLinModuleReset  = erCRASH,
    ml_erIdParity        = erIDPAR,
    ml_erCheckSum        = erCKSUM,
    ml_erBit             = erTXCOL,
    ml_erDataFraming     = erRX,
    ml_erIdFraming       = erIDSTOP,
    ml_erSynchField      = erSYNC,
    ml_erBufferLocked    = erRXOVR,
    ml_erShort           = erSHORT,
    ml_erTimeOutResponse = erTORESP,
    ml_erBreakDetected   = erBRFRM,
    ml_erWakeUpInit      = erWKUPINIT,
    ml_erStopBitTX       = mlx16_erStopBitTX   /**< Error during STOP bit transmission */
} ml_LinError_t;

/* ml_CheckSumType_t : Regular checksum (LIN v1.3) or Enhanced checksum (LIN v2.0) */
typedef enum {
    ml_chk13 = chk13,
    ml_chk20 = chk20
} ml_CheckSumType_t;

/* ml_LinState_t */
typedef enum {
    ml_stINIT         = stINIT,
    ml_stDISCONNECTED = stDISC,
    ml_stACTIVE       = stACT,
    ml_stSLEEP        = stSLEEP,
    ml_stWAKEUP       = stWKUP,
    ml_stSHORT        = stSHORT,
    ml_stINVALID      = 0xFFFF
} ml_LinState_t;

/* ml_SleepReason_t : different causes of entering Sleep State */
typedef enum {
    ml_reasonMaster          = slMST,
    ml_reasonCommand         = slAPP,
    ml_reasonWakeupAbort     = slWKUPabort,
    ml_reasonTimeOut         = slTO,
    ml_reasonTimeOutDominant = slTODOM
} ml_SleepReason_t;
#define ml_StateReason_t ml_SleepReason_t __attribute__ ((deprecated("Renamed to ml_SleepReason_t")))

typedef enum {
    ML_CLR_BUS_ACT_AND_OVF  = 0u,
    ML_CLR_LIN_CMD_OVERFLOW = 1u,
    ML_CLR_LIN_BUS_ACTIVITY = 8u,
    ML_NOT_CLEAR            = 9u
} ml_BitClear_t;

/* Protocol Mode */
typedef enum {
    ML_PM_LIN = 0,     /**< Standard LIN protocol */
    ML_PM_FASTLIN = 1  /**< Melexis specific Fast LIN protocol */
} ml_ProtocolMode_t;

typedef enum {
    ML_BR_FIXED = 0u,            /**< Fixed baudrate */
    ML_BR_AUTO_FIRST_FRAME = 1u, /**< Auto-baudrate detection on first frame */
    ML_BR_AUTO_EACH_FRAME = 2u   /**< Auto-baudrate detection on each frame */
} ml_BaudrateMode_t;

/* Auto baudrate modes */
typedef enum {
    ML_ABR_ON_FIRST_FRAME = 0u, /**< Auto-baudrate detection on first frame */
    ML_ABR_ON_EACH_FRAME = 1u   /**< Auto-baudrate detection on each frame */
} ml_AutoBaudrateMode_t;

/* Auto-addressing */
typedef enum {
    ML_AA_ENABLED = ML_TRUE,
    ML_AA_DISABLED = ML_FALSE,
    ML_AA_AUTORESET = 2u    /**< Auto-addressing pulses are generated until first ended pattern */
} ml_AutoAddressingMode_t;

/* Slew-rate */
typedef enum {
    ML_SLEWHIGH = 0u,   /* 4.5 us */
    ML_SLEWLOW = 2u,    /* 9 us   */
    ML_SLEWFAST = 1u    /* 0.2 us */
} ml_SlewRate_t;

/* ml_MessageID_t */
typedef uint8_t ml_MessageID_t;

/* ml_FrameID_t */
typedef uint8_t ml_FrameID_t;

#if (ML_HAS_EXPOSED_MEMBER_SYMBOLS == 0)
/* ml_Data_t */
typedef struct {
    /* this member shall be first as it's referenced in asm code (see mls_module.S) */
    volatile uint8_t LinFrameDataBuffer[8];

    /* ML_DATA_LIN_PRESCaler and ML_DATA_LIN_BAUD values, that will be used in ml_GetBaudRate
     * Note: up to calling application to use ml_GetBaudRate
     * when ML_DATA_LIN_BAUD and ML_DATA_LIN_PRESC were updated after the transmission */
    volatile uint8_t LINBaud;
    volatile uint8_t LINPresc;

    uint16_t LinMessage;
    volatile uint8_t LinStatus;
    volatile bool LinDiscardedFrameFlag;
} ml_Data_t;
#endif /* ML_HAS_EXPOSED_MEMBER_SYMBOLS */

#endif /* MLS_TYPES_H_ */
